// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function sourceRefFromAPI(apiSource) {
  return {
          id: apiSource.id,
          name: apiSource.name
        };
}

function fromAPI(apiArticle) {
  return {
          source: sourceRefFromAPI(apiArticle.source),
          author: apiArticle.author,
          title: apiArticle.title,
          description: apiArticle.description,
          url: apiArticle.url,
          urlToImage: apiArticle.urlToImage,
          publishedAt: new Date(apiArticle.publishedAt),
          content: apiArticle.content
        };
}

exports.sourceRefFromAPI = sourceRefFromAPI;
exports.fromAPI = fromAPI;
/* No side effect */
