// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var NewsAPI = require("./NewsAPI.bs.js");

var value = Js_dict.get(process.env, "NEWSAPI_API_KEY");

var apiKey;

if (value !== undefined) {
  apiKey = value;
} else {
  throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
}

var api = NewsAPI.make(apiKey);

var parameters = {
  hd: {
    TAG: /* Country */0,
    _0: /* Fr */15
  },
  tl: {
    hd: {
      TAG: /* Category */1,
      _0: /* Health */3
    },
    tl: /* [] */0
  }
};

var other = {
  hd: {
    TAG: /* Language */7,
    _0: /* Fr */4
  },
  tl: {
    hd: {
      TAG: /* Q */3,
      _0: "bitcoin"
    },
    tl: /* [] */0
  }
};

NewsAPI.topHeadlines(api, parameters).then(function (value) {
      return Promise.resolve((console.log(value), undefined));
    });

NewsAPI.everything(api, other).then(function (value) {
      return Promise.resolve((console.log(value), undefined));
    });

NewsAPI.sources(api, /* [] */0).then(function (value) {
      return Promise.resolve((console.log(value), undefined));
    });

exports.apiKey = apiKey;
exports.api = api;
exports.parameters = parameters;
exports.other = other;
/* value Not a pure module */
