// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function make(countryName) {
  switch (countryName) {
    case "ae" :
        return /* Ae */0;
    case "ar" :
        return /* Ar */1;
    case "at" :
        return /* At */2;
    case "au" :
        return /* Au */3;
    case "be" :
        return /* Be */4;
    case "bg" :
        return /* Bg */5;
    case "br" :
        return /* Br */6;
    case "ca" :
        return /* Ca */7;
    case "ch" :
        return /* Ch */8;
    case "cn" :
        return /* Cn */9;
    case "co" :
        return /* Co */10;
    case "cu" :
        return /* Cu */11;
    case "cz" :
        return /* Cz */12;
    case "de" :
        return /* De */13;
    case "eg" :
        return /* Eg */14;
    case "fr" :
        return /* Fr */15;
    case "gb" :
        return /* Gb */16;
    case "gr" :
        return /* Gr */17;
    case "hk" :
        return /* Hk */18;
    case "hu" :
        return /* Hu */19;
    case "id" :
        return /* Id */20;
    case "ie" :
        return /* Ie */21;
    case "il" :
        return /* Il */22;
    case "in" :
        return /* In */23;
    case "it" :
        return /* It */24;
    case "jp" :
        return /* Jp */25;
    case "kr" :
        return /* Kr */26;
    case "lt" :
        return /* Lt */27;
    case "lv" :
        return /* Lv */28;
    case "ma" :
        return /* Ma */29;
    case "mx" :
        return /* Mx */30;
    case "my" :
        return /* My */31;
    case "ng" :
        return /* Ng */32;
    case "nl" :
        return /* Nl */33;
    case "no" :
        return /* No */34;
    case "nz" :
        return /* Nz */35;
    case "ph" :
        return /* Ph */36;
    case "pl" :
        return /* Pl */37;
    case "pt" :
        return /* Pt */38;
    case "ro" :
        return /* Ro */39;
    case "rs" :
        return /* Rs */40;
    case "ru" :
        return /* Ru */41;
    case "sa" :
        return /* Sa */42;
    case "se" :
        return /* Se */43;
    case "sg" :
        return /* Sg */44;
    case "si" :
        return /* Si */45;
    case "sk" :
        return /* Sk */46;
    case "th" :
        return /* Th */47;
    case "tr" :
        return /* Tr */48;
    case "tw" :
        return /* Tw */49;
    case "ua" :
        return /* Ua */50;
    case "us" :
        return /* Us */51;
    case "ve" :
        return /* Ve */52;
    case "za" :
        return /* Za */53;
    default:
      throw {
            RE_EXN_ID: "Not_found",
            Error: new Error()
          };
  }
}

function toString(country) {
  switch (country) {
    case /* Ae */0 :
        return "ae";
    case /* Ar */1 :
        return "ar";
    case /* At */2 :
        return "at";
    case /* Au */3 :
        return "au";
    case /* Be */4 :
        return "be";
    case /* Bg */5 :
        return "bg";
    case /* Br */6 :
        return "br";
    case /* Ca */7 :
        return "ca";
    case /* Ch */8 :
        return "ch";
    case /* Cn */9 :
        return "cn";
    case /* Co */10 :
        return "co";
    case /* Cu */11 :
        return "cu";
    case /* Cz */12 :
        return "cz";
    case /* De */13 :
        return "de";
    case /* Eg */14 :
        return "eg";
    case /* Fr */15 :
        return "fr";
    case /* Gb */16 :
        return "gb";
    case /* Gr */17 :
        return "gr";
    case /* Hk */18 :
        return "hk";
    case /* Hu */19 :
        return "hu";
    case /* Id */20 :
        return "id";
    case /* Ie */21 :
        return "ie";
    case /* Il */22 :
        return "il";
    case /* In */23 :
        return "in";
    case /* It */24 :
        return "it";
    case /* Jp */25 :
        return "jp";
    case /* Kr */26 :
        return "kr";
    case /* Lt */27 :
        return "lt";
    case /* Lv */28 :
        return "lv";
    case /* Ma */29 :
        return "ma";
    case /* Mx */30 :
        return "mx";
    case /* My */31 :
        return "my";
    case /* Ng */32 :
        return "ng";
    case /* Nl */33 :
        return "nl";
    case /* No */34 :
        return "no";
    case /* Nz */35 :
        return "nz";
    case /* Ph */36 :
        return "ph";
    case /* Pl */37 :
        return "pl";
    case /* Pt */38 :
        return "pt";
    case /* Ro */39 :
        return "ro";
    case /* Rs */40 :
        return "rs";
    case /* Ru */41 :
        return "ru";
    case /* Sa */42 :
        return "sa";
    case /* Se */43 :
        return "se";
    case /* Sg */44 :
        return "sg";
    case /* Si */45 :
        return "si";
    case /* Sk */46 :
        return "sk";
    case /* Th */47 :
        return "th";
    case /* Tr */48 :
        return "tr";
    case /* Tw */49 :
        return "tw";
    case /* Ua */50 :
        return "ua";
    case /* Us */51 :
        return "us";
    case /* Ve */52 :
        return "ve";
    case /* Za */53 :
        return "za";
    
  }
}

var Country = {
  make: make,
  toString: toString
};

function toString$1(category) {
  switch (category) {
    case /* Business */0 :
        return "business";
    case /* Entertainment */1 :
        return "entertainment";
    case /* General */2 :
        return "general";
    case /* Health */3 :
        return "health";
    case /* Science */4 :
        return "science";
    case /* Sports */5 :
        return "sports";
    case /* Technology */6 :
        return "technology";
    
  }
}

var Category = {
  toString: toString$1
};

function toString$2(language) {
  switch (language) {
    case /* Ar */0 :
        return "ar";
    case /* De */1 :
        return "de";
    case /* En */2 :
        return "en";
    case /* Es */3 :
        return "es";
    case /* Fr */4 :
        return "fr";
    case /* He */5 :
        return "he";
    case /* It */6 :
        return "it";
    case /* Nl */7 :
        return "nl";
    case /* No */8 :
        return "no";
    case /* Pt */9 :
        return "pt";
    case /* Ru */10 :
        return "ru";
    case /* Se */11 :
        return "se";
    case /* Ud */12 :
        return "ud";
    case /* Zh */13 :
        return "zh";
    
  }
}

var Language = {
  toString: toString$2
};

function parameterReader(param) {
  switch (param.TAG | 0) {
    case /* Country */0 :
        return [
                "country",
                toString(param._0)
              ];
    case /* Category */1 :
        return [
                "category",
                toString$1(param._0)
              ];
    case /* Source */2 :
        return [
                "source",
                param._0
              ];
    case /* Q */3 :
        return [
                "q",
                param._0
              ];
    case /* PageSize */4 :
        return [
                "pageSize",
                String(param._0)
              ];
    case /* Page */5 :
        return [
                "Page",
                String(param._0)
              ];
    case /* APIKey */6 :
        return [
                "apiKey",
                param._0
              ];
    case /* Language */7 :
        return [
                "language",
                toString$2(param._0)
              ];
    
  }
}

function buildQuerystring(_url, _params) {
  while(true) {
    var params = _params;
    var url = _url;
    var url$1 = url !== undefined ? url : "";
    if (!params) {
      return url$1;
    }
    var match = parameterReader(params.hd);
    var prefix = url$1 === "" ? "" : "&";
    var newUrl = url$1 + prefix + match[0] + "=" + match[1];
    _params = params.tl;
    _url = newUrl;
    continue ;
  };
}

exports.Country = Country;
exports.Category = Category;
exports.Language = Language;
exports.parameterReader = parameterReader;
exports.buildQuerystring = buildQuerystring;
/* No side effect */
