// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function fromAPI(apiSource) {
  return {
          id: apiSource.id,
          name: apiSource.name,
          description: apiSource.description,
          url: apiSource.url,
          language: apiSource.language,
          country: apiSource.country
        };
}

exports.fromAPI = fromAPI;
/* No side effect */
