// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Parameter = require("../src/NewsAPI.Parameter.bs.js");

Jest.describe("Parameter tests", (function (param) {
        Jest.test("Test buildQueryString", (function (param) {
                var parameters_0 = NewsAPI.Parameter.make("name", "value");
                var parameters = {
                  hd: parameters_0,
                  tl: /* [] */0
                };
                return Jest.Expect.toBe("name=value", Jest.Expect.expect(NewsAPI.Parameter.buildQuerystring(undefined, parameters)));
              }));
        return Jest.test("Test buildQueryString with multiple parametes", (function (param) {
                      var parameters_0 = NewsAPI.Parameter.make("name", "value");
                      var parameters_1 = {
                        hd: NewsAPI.Parameter.make("otherName", "otherValue"),
                        tl: /* [] */0
                      };
                      var parameters = {
                        hd: parameters_0,
                        tl: parameters_1
                      };
                      return Jest.Expect.toBe("name=value&otherName=otherValue", Jest.Expect.expect(NewsAPI.Parameter.buildQuerystring(undefined, parameters)));
                    }));
      }));

/*  Not a pure module */
